import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import type { NormalizedFamily } from '@/types'

export async function generateDts(
  families: NormalizedFamily[],
  root: string,
): Promise<Error | null> {
  const outDir = join(root, 'node_modules', '.vite-fonts')

  try {
    await mkdir(outDir, { recursive: true })
  } catch (e) {
    return e instanceof Error ? e : new Error(String(e))
  }

  const fontEntries = families
    .map((f) => {
      const weightsLiteral = f.weights.map((w) => JSON.stringify(w)).join('; ')
      return `    ${JSON.stringify(f.key)}: { family: ${JSON.stringify(f.family)}; variable: ${JSON.stringify(f.variable)}; cssVar: ${JSON.stringify('var(' + f.variable + ')')}; weights: [${weightsLiteral}] };`
    })
    .join('\n')

  const content = `// Auto-generated by @pyyupsk/vite-fonts — do not edit
declare module "@pyyupsk/fonts" {}
declare module "@pyyupsk/fonts?url" {
  const url: string;
  export default url;
}
declare module "@pyyupsk/fonts/meta" {
  export const fonts: {
${fontEntries}
  };
}
`

  try {
    await writeFile(join(outDir, 'client.d.ts'), content, 'utf8')
  } catch (e) {
    return e instanceof Error ? e : new Error(String(e))
  }

  return null
}
